development:
  sessions:
    default:
      database: shot_visualizer_dev
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: shot_visualizer_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0


production:
  sessions:
    default:
      hosts:
        - dharma.mongohq.com:10087
      username: admin
      password: <%= ENV["MONGOHQ_PASSWORD"] %>
      database: shot_visualizer
      options:
        skip_version_check: true
        safe: true
