development:
  sessions:
    default:
      database: shot_visualizer_dev
      hosts:
        - localhost:27017
      options:
  options:

test:
  sessions:
    default:
      database: shot_visualizer_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0

<% if ENV['MONGOHQ_URL'] %>
  production:
    sessions:
      default:
        uri: <%= ENV['MONGOHQ_URL'] %>
        options:
          skip_version_check: true
          safe: true
<% end %>
